export default {
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  DELETE_ITEM: "DELETE_ITEM",

  SET_ITEM_TITLE: "SET_ITEM_TITLE",
  SET_ITEM_DESCRIPTION: "SET_ITEM_DESCRIPTION",
  SET_ITEM_ID: "SET_ITEM_ID",
  RESET_INPUT: "RESET_INPUT",

  SET_ITEM_TAG: "SET_TODO_TAG",
}