export default {
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TOOD",

  SET_TODO_TITLE: "SET_TODO_TITLE",
  SET_TODO_DESCRIPTION: "SET_TODO_DESCRIPTION",
  SET_TODO_ID: "SET_TODO_ID",
  RESET_INPUT: "RESET_INPUT",

  SET_TODO_TAG: "SET_TODO_TAG",
}